extends:
  - walmart/configurations/es6-node
rules:
  semi:
    - 2
    - never
  quotes:
    - 2
    - single
  no-console:
    - 0
  no-magic-numbers:
    - 0
  strict:
    - 0
  global-require:
    - 0
  filenames/match-regex:
    - 0
  callback-return:
    - 0
  max-statements:
    - 0
  max-nested-callbacks:
    - 0
  complexity:
    - 0
  max-params:
    - 2
    - 7
  max-depth:
    - 2
    - 6
  camelcase:
    - 0
  no-return-assign:
    - 0
  no-process-exit:
    - 0